create table public.projects (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text not null,
  description text not null,
  tags text[] null,
  looking_for text[] not null,
  max_team_size smallint null default '3'::smallint,
  leader uuid not null,
  constraint projects_pkey primary key (id),
  constraint projects_leader_fkey foreign KEY (leader) references auth.users (id) on update CASCADE on delete RESTRICT,
  constraint projects_max_team_size_check check (
    (
      (max_team_size > 2)
      and (max_team_size < 10)
    )
  )
) TABLESPACE pg_default;