create table public.projects (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text not null,
  description text not null,
  tags text[] null,
  looking_for text[] not null,
  max_team_size smallint null default '3'::smallint,
  leader uuid not null,
  constraint projects_pkey primary key (id),
  constraint projects_leader_fkey foreign KEY (leader) references auth.users (id) on update CASCADE on delete RESTRICT,
  constraint projects_max_team_size_check check (
    (
      (max_team_size > 2)
      and (max_team_size < 10)
    )
  )
) TABLESPACE pg_default;
-- Enable Row Level Security
alter table public.projects enable row level security;

-- Policies for Projects
-- Allow authenticated users to view all projects
create policy "Allow users to view all projects" on public.projects
  for select using (auth.role() = 'authenticated');

-- Allow users to insert projects for themselves
create policy "Allow users to insert own projects" on public.projects
  for insert with check (auth.uid() = leader);

-- Allow project leaders to update their own projects
create policy "Allow leaders to update own projects" on public.projects
  for update using (auth.uid() = leader);